---
# Example vars file to use when running this playbook to update any required variables
# To create backups of files modified under /tmp set to true
create_backups: true
# Enable the DoD login banner
run_etc_issue_dod: false
# Enter organizations rsyslog server
var_rsyslog_server_name: 'syslog.test.local'
var_rsyslog_server_port: '514'
## udp, tcp, or tls
var_rsyslog_server_protocol: 'tcp'
## Select package to use for time sync. ntpd(default), chrony, or timesyncd
var_time_type: 'ntpd'
# Enter organizations time servers
var_time_servers:
  - 'time-a-g.nist.gov'
  - 'time-b-g.nist.gov'
# Set to true if you want the playbook to install required packages. This requires access to a repo with the required packages.
run_rsyslog_install: true
run_openssl_fips_install: true
run_auditd_install: true
run_time_install: true
run_install_aide: true
run_selinux_install: true
# SELinux mode. 1 for enforcing and 0 for permissive
var_selinux_enforcing: 0
