---
# Turn specific controls on/off by setting the value to true or false

# Create backups of files?
create_backups: true

# PHTN-50-000003,19,31,76,78,107,173,175,204,238
run_auditd_rules: true
# PHTN-50-000004
run_pam_faillock_deny_interval: true
# PHTN-50-000005
run_sshd_banner: true
run_etc_issue_dod: true
# PHTN-50-000007
run_limits_maxlogins: true
# PHTN-50-000012
run_rsyslog_authpriv: true
# PHTN-50-000013
run_openssl_fips_install: true
run_openssl_fips: true
# PHTN-50-000014
run_auditd_conf_write_logs: true
# PHTN-50-000016
run_auditd_install: true
run_auditd_service_enable: true
# PHTN-50-000021
run_auditd_conf_actions: true
# PHTN-50-000026
run_auditd_log_perms: true
# PHTN-50-000030
run_auditd_file_perms: true
# PHTN-50-000035
run_pam_pwquality_ucredit: true
# PHTN-50-000036
run_pam_pwquality_lcredit: true
# PHTN-50-000037
run_pam_pwquality_dcredit: true
# PHTN-50-000038
run_pam_pwquality_difok: true
# PHTN-50-000039
run_login_defs_encrypt_method: true
# PHTN-50-000040
run_remove_telnet: true
# PHTN-50-000041
run_login_defs_pass_min_days: true
# PHTN-50-000042
run_login_defs_pass_max_days: true
# PHTN-50-000043
run_pam_pwhistory_remember: true
# PHTN-50-000044
run_pam_pwquality_minlen: true
# PHTN-50-000046
run_grub_boot_password: true
# PHTN-50-000047
run_modprobe_conf: true
# PHTN-50-000049
run_users_duplicate_uids: true
# PHTN-50-000059
run_pam_unix_sha512: true
# PHTN-50-000066
run_enable_selinux: true
run_selinux_install: false
# PHTN-50-000067
run_kernel_dmesg_restrict: true
# PHTN-50-000068
run_kernel_net_ipv4_tcp_syncookies: true
# PHTN-50-000069
run_sshd_clientaliveinterval: true
# PHTN-50-000073
run_var_log_perms: true
# PHTN-50-000074
run_rsyslog_umask: true
# PHTN-50-000079
run_sshd_ciphers: true
# PHTN-50-000080
run_auditd_boot_enable: true
# PHTN-50-000082
run_auditd_tools_perms: true
# PHTN-50-000085
run_usr_lib_perms: true
# PHTN-50-000086
run_pam_pwquality_ocredit: true
# PHTN-50-000092
run_auditd_rpm_verify: true
# PHTN-50-000093
run_profile_tmout_script: true
# PHTN-50-000105
run_kernel_fs_protected_symlinks: true
# PHTN-50-000108
run_pam_faillock_unlock_time: true
# PHTN-50-000110
run_auditd_conf_num_logs: true
# PHTN-50-000111
run_rsyslog_server: true
# PHTN-50-000112
run_auditd_conf_space_left: true
# PHTN-50-000121
run_time_sync: true
run_time_install: false
# PHTN-50-000127
run_install_aide: false
# PHTN-50-000130
run_tdnf_conf_gpgcheck: true
# PHTN-50-000133
run_sudo_no_password: true
# PHTN-50-000160
run_kernel_randomize_va_space: true
# PHTN-50-000161
run_tdnf_conf_clean_requirements_on_remove: true
# PHTN-50-000182
run_fips_boot_enable: true
# PHTN-50-000184
run_pam_pwquality_dictcheck: true
# PHTN-50-000185
run_login_defs_fail_delay: true
# PHTN-50-000186
run_auditd_conf_flush: true
# PHTN-50-000187
run_login_defs_umask: true
# PHTN-50-000188
run_sshd_hostbasedauthentication: true
# PHTN-50-000192
run_pam_add_faillock_so: true
# PHTN-50-000193
run_pam_faillock_silent: true
# PHTN-50-000194
run_pam_faillock_audit: true
# PHTN-50-000195
run_pam_faillock_even_deny_root: true
# PHTN-50-000196
run_pam_faillock_dir: true
# PHTN-50-000197
run_pam_add_pwquality_so: true
# PHTN-50-000199
run_yum_repos_gpgcheck: true
# PHTN-50-000200
run_sshd_syslogfacility: true
# PHTN-50-000201
run_sshd_loglevel: true
# PHTN-50-000203
run_sshd_clientalivecountmax: true
# PHTN-50-000206
run_pam_add_faildelay_so: true
# PHTN-50-000207
run_sshd_permitemptypasswords: true
# PHTN-50-000208
run_sshd_permituserenvironment: true
# PHTN-50-000209
run_login_defs_create_home: true
# PHTN-50-000210
run_disable_debug_shell_service: true
# PHTN-50-000211
run_sshd_gssapiauthentication: true
# PHTN-50-000212
run_sshd_x11forwarding: true
# PHTN-50-000213
run_sshd_strictmodes: true
# PHTN-50-000214
run_sshd_kerberosauthentication: true
# PHTN-50-000215
run_sshd_compression: true
# PHTN-50-000216
run_sshd_printlastlog: true
# PHTN-50-000217
run_sshd_ignorerhosts: true
# PHTN-50-000218
run_sshd_ignoreuserknownhosts: true
# PHTN-50-000219
run_sshd_maxauthtries: true
# PHTN-50-000220
run_sshd_allowtcpforwarding: true
# PHTN-50-000221
run_sshd_logingracetime: true
# PHTN-50-000222
run_disable_ctrl_alt_del_service: true
# PHTN-50-000223
run_kernel_net_accept_source_route: true
# PHTN-50-000224
run_kernel_net_ipv4_icmp_echo_ignore_broadcasts: true
# PHTN-50-000225
run_kernel_net_accept_redirects: true
# PHTN-50-000226
run_kernel_net_secure_redirects: true
# PHTN-50-000227
run_kernel_net_send_redirects: true
# PHTN-50-000228
run_kernel_net_log_martians: true
# PHTN-50-000229
run_kernel_net_rp_filter: true
# PHTN-50-000231
run_kernel_net_ip_forward: true
# PHTN-50-000232
run_kernel_net_tcp_timestamps: true
# PHTN-50-000233
run_sshd_pub_key_permissions: true
# PHTN-50-000234
run_sshd_pri_key_permissions: true
# PHTN-50-000235
run_pam_pwquality_enforce_for_root: true
# PHTN-50-000236
run_systemd_fallback_dns: true
# PHTN-50-000238
run_aide_config: true
# PHTN-50-000239
run_sshd_macs: true
# PHTN-50-000241
run_rsyslog_install: true
# PHTN-50-000242
run_rsyslog_enable: true
# PHTN-50-000243
run_pam_pwhistory_module: true
# PHTN-50-000244
run_kernel_fs_protected_hardlinks: true
# PHTN-50-000245
run_systemd_tmp_mount: true
# PHTN-50-000246
run_kernel_fs_suid_dumpable: true
