---
# Pull Photon role
roles:
  - src: https://github.com/vmware/dod-compliance-and-automation/tree/master/photon/3.0/ansible/vmware-photon-3.0-stig-ansible-hardening
    scm: git
    version: master

collections:
  - name: community.general
  - name: ansible.posix
