---
# Turn specific controls on/off by setting the value to true or false

# Create backups of files?
create_backups: true

# PHTN-40-000003,19,31,76,78,107,173,175,204,238
run_auditd_rules: true
# PHTN-40-000004
run_pam_faillock_deny_interval: true
# PHTN-40-000005
run_sshd_banner: true
run_etc_issue_dod: false
# PHTN-40-000007
run_limits_maxlogins: true
# PHTN-40-000012
run_rsyslog_authpriv: true
# PHTN-40-000013
run_openssl_fips_install: true
run_openssl_fips: true
# PHTN-40-000014
run_auditd_conf_write_logs: true
# PHTN-40-000016
run_auditd_install: true
run_auditd_service_enable: true
# PHTN-40-000021
run_auditd_conf_actions: true
# PHTN-40-000026
run_auditd_log_perms: true
# PHTN-40-000030
run_auditd_file_perms: true
# PHTN-40-000035
run_pam_pwquality_ucredit: true
# PHTN-40-000036
run_pam_pwquality_lcredit: true
# PHTN-40-000037
run_pam_pwquality_dcredit: true
# PHTN-40-000038
run_pam_pwquality_difok: true
# PHTN-40-000039
run_login_defs_encrypt_method: true
# PHTN-40-000040
run_remove_telnet: true
# PHTN-40-000041
run_login_defs_pass_min_days: true
# PHTN-40-000042
run_login_defs_pass_max_days: true
# PHTN-40-000043
run_pam_pwhistory_remember: true
# PHTN-40-000044
run_pam_pwquality_minlen: true
# PHTN-40-000046
run_grub_boot_password: true
# PHTN-40-000047
run_modprobe_conf: true
# PHTN-40-000049
run_users_duplicate_uids: true
# PHTN-40-000059
run_pam_unix_sha512: true
# PHTN-40-000066
run_enable_selinux: false
run_selinux_install: false
# PHTN-40-000067
run_kernel_dmesg_restrict: true
# PHTN-40-000068
run_kernel_net_ipv4_tcp_syncookies: true
# PHTN-40-000069
run_sshd_clientaliveinterval: true
# PHTN-40-000073
run_var_log_perms: true
# PHTN-40-000074
run_rsyslog_umask: true
# PHTN-40-000079
run_sshd_ciphers: true
# PHTN-40-000080
run_auditd_boot_enable: true
# PHTN-40-000082
run_auditd_tools_perms: true
# PHTN-40-000085
run_usr_lib_perms: true
# PHTN-40-000086
run_pam_pwquality_ocredit: true
# PHTN-40-000092
run_auditd_rpm_verify: true
# PHTN-40-000093
run_profile_tmout_script: true
# PHTN-40-000105
run_kernel_fs_protected_symlinks: true
# PHTN-40-000108
run_pam_faillock_unlock_time: true
# PHTN-40-000110
run_auditd_conf_num_logs: true
# PHTN-40-000111
run_rsyslog_server: true
# PHTN-40-000112
run_auditd_conf_space_left: true
# PHTN-40-000121
run_time_sync: false
run_time_install: false
# PHTN-40-000127
run_install_aide: true
# PHTN-40-000130
run_tdnf_conf_gpgcheck: true
# PHTN-40-000133
run_sudo_no_password: true
# PHTN-40-000160
run_kernel_randomize_va_space: true
# PHTN-40-000161
run_tdnf_conf_clean_requirements_on_remove: true
# PHTN-40-000182
run_fips_boot_enable: false
# PHTN-40-000184
run_pam_pwquality_dictcheck: true
# PHTN-40-000185
run_login_defs_fail_delay: true
# PHTN-40-000186
run_auditd_conf_flush: true
# PHTN-40-000187
run_login_defs_umask: true
# PHTN-40-000188
run_sshd_hostbasedauthentication: true
# PHTN-40-000192
run_pam_add_faillock_so: true
# PHTN-40-000193
run_pam_faillock_silent: true
# PHTN-40-000194
run_pam_faillock_audit: true
# PHTN-40-000195
run_pam_faillock_even_deny_root: true
# PHTN-40-000196
run_pam_faillock_dir: true
# PHTN-40-000197
run_pam_add_pwquality_so: true
# PHTN-40-000199
run_yum_repos_gpgcheck: true
# PHTN-40-000200
run_sshd_syslogfacility: true
# PHTN-40-000201
run_sshd_loglevel: true
# PHTN-40-000203
run_sshd_clientalivecountmax: true
# PHTN-40-000206
run_pam_add_faildelay_so: true
# PHTN-40-000207
run_sshd_permitemptypasswords: true
# PHTN-40-000208
run_sshd_permituserenvironment: true
# PHTN-40-000209
run_login_defs_create_home: true
# PHTN-40-000210
run_disable_debug_shell_service: true
# PHTN-40-000211
run_sshd_gssapiauthentication: true
# PHTN-40-000212
run_sshd_x11forwarding: true
# PHTN-40-000213
run_sshd_strictmodes: true
# PHTN-40-000214
run_sshd_kerberosauthentication: true
# PHTN-40-000215
run_sshd_compression: true
# PHTN-40-000216
run_sshd_printlastlog: true
# PHTN-40-000217
run_sshd_ignorerhosts: true
# PHTN-40-000218
run_sshd_ignoreuserknownhosts: true
# PHTN-40-000219
run_sshd_maxauthtries: true
# PHTN-40-000220
run_sshd_allowtcpforwarding: true
# PHTN-40-000221
run_sshd_logingracetime: true
# PHTN-40-000222
run_disable_ctrl_alt_del_service: true
# PHTN-40-000223
run_kernel_net_accept_source_route: true
# PHTN-40-000224
run_kernel_net_ipv4_icmp_echo_ignore_broadcasts: true
# PHTN-40-000225
run_kernel_net_accept_redirects: true
# PHTN-40-000226
run_kernel_net_secure_redirects: true
# PHTN-40-000227
run_kernel_net_send_redirects: true
# PHTN-40-000228
run_kernel_net_log_martians: true
# PHTN-40-000229
run_kernel_net_rp_filter: true
# PHTN-40-000231
run_kernel_net_ip_forward: true
# PHTN-40-000232
run_kernel_net_tcp_timestamps: true
# PHTN-40-000233
run_sshd_pub_key_permissions: true
# PHTN-40-000234
run_sshd_pri_key_permissions: true
# PHTN-40-000235
run_pam_pwquality_enforce_for_root: true
# PHTN-40-000236
run_systemd_fallback_dns: true
# PHTN-40-000238
run_aide_config: true
# PHTN-40-000239
run_sshd_macs: true
# PHTN-40-000241
run_rsyslog_install: true
# PHTN-40-000242
run_rsyslog_enable: true
# PHTN-40-000243
run_pam_pwhistory_module: true
# PHTN-40-000244
run_kernel_fs_protected_hardlinks: true
# PHTN-40-000245
run_systemd_tmp_mount: true
# PHTN-40-000246
run_kernel_fs_suid_dumpable: true
# PHTN-40-000247
run_pam_remove_nullok: true
