# perfcharts variables

# server.xml variables
var_server_xml_path: '/usr/lib/vmware-perfcharts/tc-instance/conf/server.xml'
var_server_xml_connectiontimeout: '20000'
var_server_xml_maxthreads: '300'
# This may need special escaping if special characters are used like & and {# #}  {% raw %} and {% endraw %} at the beginning and end will get most of it
# Also & needs to just be a " which turns into &quot
var_server_xml_access_log_valve_pattern: '{% raw %}%h %{X-Forwarded-For}i %l %u %t "%r" %s %b "%{User-Agent}i"{% endraw %}'
var_server_xml_acceptcount: '300'
var_server_xml_uriencoding: 'UTF-8'

# web.xml variables
var_web_xml_path: '/usr/lib/vmware-perfcharts/tc-instance/conf/web.xml'
var_web_stats_xml_path: '/usr/lib/vmware-perfcharts/tc-instance/webapps/statsreport/WEB-INF/web.xml'
var_web_xml_http_only: 'true'
var_web_xml_servlet_jsp_url_pattern1: '*.jsp'
var_web_xml_servlet_jsp_url_pattern2: '*.jspx'
var_web_xml_welcome_file_list1: 'index.html'
var_web_xml_welcome_file_list2: 'index.htm'
var_web_xml_welcome_file_list3: 'index.jsp'
var_web_xml_error_page: '/http_error.jsp'
var_web_xml_cookie_secure: 'true'

# perfcharts.json variables
var_json_path: '//etc/vmware/vmware-vmon/svcCfgfiles/perfcharts.json'
var_stream_redirect_file: '%VMWARE_LOG_DIR%/vmware/perfcharts/vmware-perfcharts-runtime.log'

# perfcharts log variables
var_perf_logs_path: '/storage/log/vmware/perfcharts'
var_perf_log4j_path: '/etc/vmware-perfcharts/log4j.properties'
var_perf_log4j_maxfilesize: '5MB'
var_perf_log4j_maxbackupindex: '10'

# catalina properties variables
var_catalina_props_path: '/usr/lib/vmware-perfcharts/tc-instance/conf/catalina.properties'

# misc variables
var_perfcharts_web_path: '/usr/lib/vmware-perfcharts/tc-instance/webapps'
