# eam variables

# server.xml variables
var_server_xml_path: '/usr/lib/vmware-eam/web/conf/server.xml'
var_server_xml_connectiontimeout: '20000'
var_server_xml_maxthreads: '300'
# This may need special escaping if special characters are used like & and {# #}  {% raw %} and {% endraw %} at the beginning and end will get most of it
# Also & needs to just be a " which turns into &quot
var_server_xml_access_log_valve_pattern: '{% raw %}%h %{X-Forwarded-For}i %l %u %t [%I] "%r" %s %b [Processing time %D msec] "%{User-Agent}i"{% endraw %}'
var_server_xml_acceptcount: '300'
var_server_xml_uriencoding: 'UTF-8'

# web.xml variables
var_web_xml_path: '/usr/lib/vmware-eam/web/webapps/eam/WEB-INF/web.xml'
var_web_xml_http_only: 'true'
var_web_xml_servlet_jsp_url_pattern: '*.jsp'
var_web_xml_filter_class: 'org.apache.catalina.filters.SetCharacterEncodingFilter'
var_web_xml_welcome_file_list: 'index.jsp'
var_web_xml_error_page: '/error.jsp'
var_web_xml_cookie_secure: 'true'

# eam.json variables
var_eam_json_path: '/etc/vmware/vmware-vmon/svcCfgfiles/eam.json'
var_stream_redirect_file: '%VMWARE_LOG_DIR%/vmware/eam/jvm.log'

# eam log variables
var_eam_logs_path: '/var/log/vmware/eam/web/'

# catalina properties variables
var_catalina_props_path: '/etc/vmware-eam/catalina.properties'

# misc variables
var_eam_web_path: '/usr/lib/vmware-eam/web/'
