name: Check code for syntax issues

on:
  push:
  pull_request:

jobs:
  cookstyle-vsphere70:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Testing
        run: |
          gem list
          cookstyle --version
      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-check
          skip_install: true
          use_bundler: true
          rubocop_flags: --config .rubocop.yml
          workdir: ./vsphere/7.0
  ansiblelint-vsphere70:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      # - name: Copy Photon playbook to roles folder
      #   run: |
      #     echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      #     ls -la $GITHUB_WORKSPACE
      #     mkdir -p /usr/share/ansible/roles/vmware-photon-3.0-stig-ansible-hardening
      #     cp -r $GITHUB_WORKSPACE/photon/3.0/ansible/vmware-photon-3.0-stig-ansible-hardening/roles/*/* /usr/share/ansible/roles/vmware-photon-3.0-stig-ansible-hardening/
      #     mkdir -p /usr/share/ansible/roles/vmware-photon-3.0-stig-ansible-hardening/vmware-photon-3.0-stig-ansible-hardening
      #     cp $GITHUB_WORKSPACE/photon/3.0/ansible/vmware-photon-3.0-stig-ansible-hardening/*.* /usr/share/ansible/roles/vmware-photon-3.0-stig-ansible-hardening/vmware-photon-3.0-stig-ansible-hardening/
      #     ls -la /usr/share/ansible/roles
      #     ansible-galaxy role list
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vsphere/7.0/vcsa/ansible/vmware-vcsa-7.0-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-vsphere80:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./vsphere/8.0
  # ansiblelint-vsphere80:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "vsphere/8.0/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-photon30:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./photon/3.0
  # ansiblelint-photon30:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "photon/3.0/ansible/vmware-photon-3.0-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-photon40:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./photon/4.0
  # ansiblelint-photon40:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "photon/4.0/ansible/vmware-photon-4.0-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-photon50:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./photon/5.0
  # ansiblelint-photon50:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "photon/5.0/ansible/vmware-photon-5.0-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-vcd104:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./vcd/10.4
  # ansiblelint-vcd104:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "vcd/10.4/ansible/vmware-cloud-director-10.4-stig-ansible-hardening/"  # <-- only one value is allowed
  # cookstyle-horizon-8:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./horizon/8.0
  # cookstyle-vra-8:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         cookstyle ./aria/automation/8.x/
  # cookstyle-vcf4:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./vcf/4.x
  # cookstyle-vcf5:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./vcf/5.x
  # ansiblelint-vcf5:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "vcf/5.x/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/"
  # cookstyle-nsx3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./nsx/3.x/inspec/vmware-nsxt-3.x-stig-baseline
  # cookstyle-nsx4:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./nsx/4.x/inspec/vmware-nsx-4.x-stig-baseline
  # cookstyle-nsxalb:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - name: Setup Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 2.7
  #         bundler-cache: true
  #     - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
  #     - name: Install cookstyle and run
  #       run: |
  #         gem install cookstyle
  #         ls -la
  #         cookstyle ./nsx-alb/30.x/inspec/vmware-nsx-alb-stig-baseline
  # ansiblelint-nsx3:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "nsx/3.x/ansible/vmware-nsxt-3.x-stig-ansible-hardening/"
  # ansiblelint-nsx4:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v3
  #     - uses: ansible-community/ansible-lint-action@main
  #       with:
  #         path: "nsx/4.x/ansible/vmware-nsx-4.x-stig-ansible-hardening/"
