name: Lint code for syntax issues on pull requests

on:
  pull_request:

jobs:
  lint-inspec-all:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-check
          skip_install: true
          use_bundler: true
          fail_on_error: true
          rubocop_flags: --config /home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/.rubocop.yml
          workdir: .
  ansiblelint-aria-lcm-v1r2-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "aria/lifecycle/8.x/v1r2-srg/ansible/vmware-vrslcm-8.x-stig-ansible-hardening/"
  ansiblelint-aria-logs-v1r4-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "aria/operations-for-logs/8.x/v1r4-srg/ansible/vmware-vrli-8.x-stig-ansible-hardening/"
  ansiblelint-aria-ops-v1r2-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "aria/operations/8.x/v1r2-srg/ansible/vmware-aria-operations-8x-stig-ansible-hardening/"
  ansiblelint-nsx3-v1r3-stig:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "nsx/3.x/v1r3-stig/ansible/vmware-nsxt-3.x-stig-ansible-hardening/"
  ansiblelint-nsx4-v1r1-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "nsx/4.x/v1r1-srg/ansible/vmware-nsx-4.x-stig-ansible-hardening/"
  ansiblelint-nsx4-v1r2-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "nsx/4.x/v1r2-srg/ansible/vmware-nsx-4.x-stig-ansible-hardening/"
  ansiblelint-photon3-v1r9-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "photon/3.0/v1r9-srg/ansible/vmware-photon-3.0-stig-ansible-hardening/"
  ansiblelint-photon4-v1r5-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "photon/4.0/v1r5-srg/ansible/vmware-photon-4.0-stig-ansible-hardening/"
  ansiblelint-photon5-v1r3-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "photon/5.0/v1r3-srg/ansible/vmware-photon-5.0-stig-ansible-hardening/"
  ansiblelint-vcd10x-v1r1-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vcd/10.x/v1r1-srg/ansible/vmware-cloud-director-10.x-stig-ansible-hardening/"
  ansiblelint-vcf5x-v1r1-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vcf/5.x/v1r1-srg/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/"
  ansiblelint-vcf5x-v1r2-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vcf/5.x/v1r2-srg/ansible/vmware-cloud-foundation-sddcmgr-5x-stig-ansible-hardening/"
  ansiblelint-vsphere70:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vsphere/7.0/v1r3-stig/vcsa/ansible/vmware-vcsa-7.0-stig-ansible-hardening/"
  ansiblelint-vsphere80-v1r1-srg:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vsphere/8.0/v1r1-srg/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/"
  ansiblelint-vsphere80-v1r1-stig:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vsphere/8.0/v1r1-stig/vcsa/ansible/vmware-vcsa-8.0-stig-ansible-hardening/"
