name: Check code for syntax issues

on:
  push:
  pull_request:

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
      - name: Install cookstyle and run
        run: |
          gem install cookstyle
          cookstyle ./
  ansiblelint-vsphere67:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - uses: ansible-community/ansible-lint-action@main
        with:
          path: "vsphere/6.7/vcsa/ansible/vmware-vcsa-6.7-stig-ansible-hardening/"  # <-- only one value is allowed
